[tool.poetry]
name = "ll"
version = "0.1.0"
description = ""
authors = ["liamcollins <liam.collins@columbia.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
